import type { ReactNode } from "react";
import type { EndpointContextSnapshot, BaselineSectionsV1, InventorySectionsV1 } from "./endpoint-context-types";
import { ContextFacts, contextBytes, contextDate } from "./endpoint-context-view";

function ContextTable({ headers, rows }: { headers: ReadonlyArray<string>; rows: ReadonlyArray<ReadonlyArray<ReactNode>> }) {
  if (!rows.length) return <p className="text-sm text-slate-500">Нет данных в наблюдении Endpoint.</p>;
  return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{headers.map(label => <th className="p-3 text-slate-500" key={label}>{label}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index} className="border-t border-border">{row.map((value, cell) => <td className="break-words p-3" key={cell}>{value ?? "Нет данных"}</td>)}</tr>)}</tbody></table></div>;
}
export function ContextSystem({ inventory, baseline }: { inventory?: InventorySectionsV1; baseline?: BaselineSectionsV1 }) {
  if (inventory) return <div className="space-y-6"><ContextFacts rows={[["Hostname", inventory.system.hostname], ["ОС", inventory.system.os_name], ["Версия / сборка ОС", [inventory.system.os_version, inventory.system.os_build].filter(Boolean).join(" ") || null], ["Архитектура", inventory.system.architecture], ["Производитель", inventory.hardware.manufacturer], ["Модель", inventory.hardware.model], ["Серийный номер", inventory.hardware.serial_number], ["CPU", inventory.hardware.cpu_model], ["RAM", contextBytes(inventory.memory.total_bytes)], ["Тип RAM", inventory.memory.memory_type], ["BIOS", [inventory.hardware.bios_vendor, inventory.hardware.bios_version].filter(Boolean).join(" ") || null], ["Системная плата", [inventory.hardware.baseboard_manufacturer, inventory.hardware.baseboard_model].filter(Boolean).join(" ") || null]]}/>
    <h3 className="font-semibold">Модули памяти · {inventory.memory.module_count}</h3><ContextTable headers={["Слот", "Производитель / артикул", "Объём", "Тип", "Скорость"]} rows={inventory.memory.modules.map(module => [module.slot, [module.manufacturer, module.part_number].filter(Boolean).join(" ") || null, contextBytes(module.capacity_bytes), module.memory_type, module.speed_mt_s == null ? null : `${module.speed_mt_s} MT/s`])}/>
    <h3 className="font-semibold">Накопители</h3><ContextTable headers={["Модель", "Серийный номер", "Объём", "Тип / шина"]} rows={inventory.storage.physical_devices.map(storage => [storage.model, storage.serial, contextBytes(storage.size_bytes), `${storage.media_type} / ${storage.bus_type}`])}/></div>;
  if (baseline) return <div className="space-y-6"><ContextFacts rows={[["Платформа", baseline.system.platform], ["ОС", baseline.system.distribution], ["Архитектура", baseline.system.architecture], ["Производитель", baseline.hardware.manufacturer], ["Модель", baseline.hardware.model], ["CPU", baseline.hardware.cpu_model], ["RAM", contextBytes(baseline.hardware.memory_bytes)]]}/><ContextTable headers={["Накопитель", "Объём"]} rows={baseline.storage.map(storage => [storage.model, contextBytes(storage.size_bytes)])}/></div>;
  return <p>Системный контекст ещё не собран.</p>;
}
export function ContextSnapshotContent({ snapshot, section }: { snapshot: EndpointContextSnapshot; section?: "system" | "network" | "software" }) {
  return <div className="space-y-5"><p className="text-xs text-slate-500">Endpoint · {snapshot.profile} · Собрано {contextDate(snapshot.collected_at)}</p>{snapshot.warnings.length > 0 && <p role="status" className="rounded-xl bg-amber-50 p-3 text-sm">Предупреждения наблюдения: {snapshot.warnings.join(", ")}</p>}
    {snapshot.profile === "inventory_v1" && (section === "network" ? <ContextTable headers={["Интерфейс", "MAC", "IP", "Состояние"]} rows={snapshot.sections.interfaces.map(network => [network.name, network.mac, [...network.ipv4, ...network.ipv6].join(", ") || null, network.operational_state])}/> : <ContextSystem inventory={snapshot.sections}/>)}
    {snapshot.profile === "baseline_v1" && (section === "software" ? <ContextTable headers={["Программа", "Версия", "Источник"]} rows={snapshot.sections.software.map(software => [software.name, software.version, software.source])}/> : section === "network" ? <ContextTable headers={["Интерфейс", "Тип"]} rows={snapshot.sections.interfaces.map(network => [network.name, network.link_type])}/> : <ContextSystem baseline={snapshot.sections}/>)}
    {snapshot.profile === "network_v1" && <><ContextFacts rows={[["Основной интерфейс", snapshot.sections.default_route.interface], ["Шлюз", snapshot.sections.default_route.gateway]]}/><ContextTable headers={["Интерфейс", "Адреса"]} rows={snapshot.sections.interfaces.map(network => [network.name, network.addresses.join(", ") || null])}/></>}
    {snapshot.profile === "health_v1" && <><ContextFacts rows={[["Uptime, секунд", snapshot.sections.resources.uptime_seconds], ["Load 1m", snapshot.sections.resources.load_1m], ["Свободное пространство", contextBytes(snapshot.sections.resources.free_bytes)]]}/><ContextTable headers={["Служба", "Состояние"]} rows={snapshot.sections.services.map(service => [service.name, service.status])}/></>}
    {snapshot.profile === "session_v1" && <ContextFacts rows={[["Наблюдаемый login", snapshot.sections.current_user_login], ["Интерактивная сессия", snapshot.sections.interactive_session_present ? "Обнаружена" : "Не обнаружена"]]}/>}
  </div>;
}
