"""Public external-domain ports and their fail-closed composition defaults."""

from .container import DomainPortContainer
from .endpoint import EndpointAvailability, EndpointPort
from .knowledge import (
    KnowledgeAvailability,
    KnowledgeAvailabilityOutcome,
    KnowledgeFeedbackOutcome,
    KnowledgeFeedbackRequest,
    KnowledgeFeedbackResult,
    KnowledgeItemProjection,
    KnowledgePort,
    KnowledgeReadResult,
    KnowledgeResolutionDraftOutcome,
    KnowledgeResolutionDraftRequest,
    KnowledgeResolutionDraftResult,
    KnowledgeSearchRequest,
    KnowledgeSearchResult,
    KnowledgeSuggestionRequest,
    KnowledgeUnavailable,
)
from .registry import RegistryAvailability, RegistryPort
from .registry_contracts import (
    AccountStatusOutcome,
    AccountStatusProjection,
    ActiveBindingOutcome,
    ActiveBindingProjection,
    ActorRef,
    AudienceProjection,
    AudienceProjectionOutcome,
    AudienceRef,
    BindingRef,
    BindingRevocationRequest,
    DeviceRef,
    OpaqueRegistryRef,
    PersonRef,
    RegistrationApprovalRequest,
    RegistrationRef,
    RegistrationRequest,
    RegistryCommandResult,
    RegistryNotFound,
    RegistryUnavailable,
    RequesterRef,
    RequesterSnapshot,
    RequesterSnapshotOutcome,
    requester_persistence_values,
)
from .unavailable import UnavailableEndpointPort, UnavailableKnowledgePort, UnavailableRegistryPort

__all__ = (
    "DomainPortContainer",
    "EndpointAvailability",
    "EndpointPort",
    "KnowledgeAvailability",
    "KnowledgeAvailabilityOutcome",
    "KnowledgeFeedbackOutcome",
    "KnowledgeFeedbackRequest",
    "KnowledgeFeedbackResult",
    "KnowledgeItemProjection",
    "KnowledgePort",
    "KnowledgeReadResult",
    "KnowledgeResolutionDraftOutcome",
    "KnowledgeResolutionDraftRequest",
    "KnowledgeResolutionDraftResult",
    "KnowledgeSearchRequest",
    "KnowledgeSearchResult",
    "KnowledgeSuggestionRequest",
    "KnowledgeUnavailable",
    "AccountStatusOutcome",
    "AccountStatusProjection",
    "ActiveBindingOutcome",
    "ActiveBindingProjection",
    "ActorRef",
    "AudienceProjection",
    "AudienceProjectionOutcome",
    "AudienceRef",
    "BindingRef",
    "BindingRevocationRequest",
    "DeviceRef",
    "OpaqueRegistryRef",
    "PersonRef",
    "RegistrationApprovalRequest",
    "RegistrationRef",
    "RegistrationRequest",
    "RegistryCommandResult",
    "RegistryNotFound",
    "RegistryUnavailable",
    "RegistryAvailability",
    "RegistryPort",
    "RequesterRef",
    "RequesterSnapshot",
    "RequesterSnapshotOutcome",
    "requester_persistence_values",
    "UnavailableEndpointPort",
    "UnavailableKnowledgePort",
    "UnavailableRegistryPort",
)
