"""
Регистрация всех маршрутов приложения.
"""

from aiohttp import web

# Import handlers from modules
from auth.handlers import handle_login, handle_ui_login, handle_ui_session
from auth.connection_request_handlers import (
    handle_connection_request,
    handle_connection_request_status,
    handle_admin_connection_policy_get,
    handle_admin_connection_policy_patch,
    handle_admin_connection_requests_list,
    handle_admin_connection_request_approve,
    handle_admin_connection_request_reject,
)
from auth.admin_users_handlers import (
    handle_admin_users_list,
    handle_admin_users_post,
    handle_admin_users_get,
    handle_admin_users_patch,
    handle_admin_users_password_post,
    handle_admin_users_deactivate_post,
    handle_users_me_password_post,
)
from tickets.public_queue_handlers import (
    handle_public_queues,
    handle_public_queue_tickets,
    handle_public_queue_stats,
)
from tickets.public_ticket_handlers import (
    handle_public_ticket_authorize,
    handle_public_ticket_create,
)
from web_api.quality_handlers import (
    handle_public_ticket_feedback,
    handle_public_ticket_reopen,
    handle_quality_improvement_action_close,
    handle_quality_improvement_action_patch,
    handle_quality_improvement_actions,
    handle_quality_improvement_actions_create,
    handle_quality_policies,
    handle_quality_policies_save,
    handle_quality_reviews,
    handle_quality_reviews_assign,
    handle_quality_reviews_complete,
    handle_quality_reviews_dismiss,
    handle_quality_reviews_start,
    handle_quality_service_quality,
    handle_quality_snapshots_recompute,
    handle_quality_summary,
    handle_ticket_feedback,
    handle_ticket_reopen,
)
from web_api.problem_handlers import (
    handle_web_problem_affected_objects,
    handle_web_problem_candidate_convert,
    handle_web_problem_candidate_merge,
    handle_web_problem_candidates,
    handle_web_problem_candidates_scan,
    handle_web_problem_get,
    handle_web_problem_known_error_draft,
    handle_web_problem_link_ticket,
    handle_web_problem_metrics_summary,
    handle_web_problem_rca_approve,
    handle_web_problem_rca_create,
    handle_web_problem_rca_submit,
    handle_web_problem_scanner_run,
    handle_web_problem_scanner_runs,
    handle_web_problem_scanner_status,
    handle_web_problem_transition,
    handle_web_problem_unlink_ticket,
    handle_web_problem_workaround_draft,
    handle_web_problems_create,
    handle_web_problems_list,
)
from web_api.change_handlers import (
    handle_web_change_approval_decide,
    handle_web_change_approvals_request,
    handle_web_change_from_improvement_action,
    handle_web_change_from_problem,
    handle_web_change_get,
    handle_web_change_metrics_summary,
    handle_web_change_pir_approve,
    handle_web_change_pir_create,
    handle_web_change_pir_submit,
    handle_web_change_plan_approve,
    handle_web_change_plan_create,
    handle_web_change_policies,
    handle_web_change_policies_preview,
    handle_web_change_policies_save,
    handle_web_change_risk_approve,
    handle_web_change_risk_create,
    handle_web_change_risk_submit,
    handle_web_change_schedule,
    handle_web_change_task_complete,
    handle_web_change_task_create,
    handle_web_change_tasks,
    handle_web_change_transition,
    handle_web_change_windows,
    handle_web_change_windows_create,
    handle_web_changes_create,
    handle_web_changes_list,
)
from web_api.approval_handlers import handle_web_support_approvals
from customer_history.handlers import (
    handle_web_admin_history_search,
    handle_web_requester_history,
    handle_web_requester_ticket_history,
    handle_web_support_person_history,
    handle_web_support_ticket_context_pack,
    handle_web_support_ticket_history,
    handle_web_support_ticket_llm_context_preview,
)
from web_api.requester_handlers import (
    handle_web_requester_bootstrap,
    handle_web_requester_consent_approve,
    handle_web_requester_consent_deny,
    handle_web_requester_consent_detail,
    handle_web_requester_consents,
    handle_web_requester_device_detail,
    handle_web_requester_devices,
    handle_web_requester_on_behalf_people,
    handle_web_requester_profile,
    handle_web_requester_profile_update,
    handle_web_requester_ticket_claim_public,
    handle_web_requester_ticket_close,
    handle_web_requester_ticket_create,
    handle_web_requester_ticket_detail,
    handle_web_requester_ticket_feedback,
    handle_web_requester_ticket_message,
    handle_web_requester_ticket_preview,
    handle_web_requester_ticket_reopen,
    handle_web_requester_tickets,
)
from tickets.form_pack_handlers import (
    handle_ticket_form_pack_current,
    handle_ticket_form_pack_detail,
    handle_ticket_form_pack_save,
    handle_ticket_form_pack_set_preferred,
    handle_ticket_form_packs_list,
)
from tickets.handlers import (
    handle_tickets_create,
    handle_tickets_create_preview,
    handle_ticket_get,
    handle_tickets_list,
    handle_ticket_send_message,
    handle_ticket_close,
    handle_ticket_status,
    handle_ticket_get_snapshot,
    handle_ticket_get_observer_summary,
    handle_ticket_reroute,
    handle_ticket_classify,
    handle_ticket_queue,
    handle_ticket_priority,
    handle_ticket_order,
    handle_ticket_queue_order_reset,
    handle_ticket_assign,
    handle_tickets_archive,
    handle_tickets_bulk_assign,
    handle_ticket_bind_device,
    handle_ticket_mark_read,
    handle_ticket_requester_profile,
    handle_ticket_sla_get,
    handle_ticket_worklogs_post,
    handle_ticket_worklogs_list,
    handle_ticket_worklog_total,
    handle_ticket_links_post,
    handle_ticket_links_list,
    handle_ticket_links_delete,
    handle_ticket_parent_post,
    handle_ticket_parent_delete,
    handle_ticket_watchers_post,
    handle_ticket_watchers_list,
    handle_ticket_watchers_delete,
    handle_ticket_resolution_codes_list,
    handle_ticket_metrics_backlog,
    handle_ticket_metrics_aging,
    handle_ticket_metrics_sla,
    handle_ticket_metrics_reopen_rate,
    handle_ticket_metrics_top,
    handle_ticket_metrics_status_age,
    handle_notifications_list,
    handle_notifications_unread_count,
    handle_notifications_read_all,
    handle_notification_preferences_get,
    handle_notification_preferences_post,
    handle_notification_mark_read,
    handle_problems_create,
    handle_problems_list,
    handle_problem_get,
    handle_problem_status_post,
    handle_problem_tickets_post,
    handle_problem_tickets_delete,
    handle_ticket_problems_get,
    handle_ticket_change_links_post,
    handle_ticket_change_links_list,
    handle_ticket_change_links_delete,
)
from playbook_handlers import handle_start_playbook_run
from websocket.ui_handler import websocket_ui_handler
from uploads.handlers import handle_upload, handle_artifact_download
from static_pages.handlers import (
    handle_index,
    handle_admin_page,
    handle_login_page,
    handle_support_page,
    handle_favicon,
    handle_ticket_page,
    handle_ticket_page_by_id,
    handle_test_simple,
    handle_ws_ui_test,
    handle_public_queue_page,
    handle_public_queue_css,
    handle_public_queue_js,
    handle_help_page,
)
from static_pages.webapp_assets import (
    handle_webapp_asset,
    handle_webapp_page,
    handle_webapp_public_asset,
)
from tickets.admin_config_handlers import (
    handle_admin_queues_list,
    handle_admin_queues_post,
    handle_admin_queues_get,
    handle_admin_queues_patch,
    handle_admin_queue_members_list,
    handle_admin_queue_members_put,
    handle_admin_queue_members_delete,
    handle_admin_resolution_codes_list,
    handle_admin_resolution_codes_post,
    handle_admin_resolution_codes_patch,
    handle_admin_resolution_codes_delete,
    handle_admin_routing_rules_list,
    handle_admin_routing_rules_post,
    handle_admin_routing_rules_patch,
    handle_admin_sla_policies_list,
    handle_admin_sla_policies_post,
    handle_admin_sla_policies_patch,
    handle_admin_sla_policies_set_default,
    handle_admin_sla_targets_get,
    handle_admin_sla_targets_put,
    handle_admin_priority_matrix_get,
    handle_admin_priority_matrix_put,
    handle_admin_calendars_list,
    handle_admin_calendars_post,
    handle_admin_calendars_patch,
    handle_admin_ola_targets_get,
    handle_admin_ola_targets_put,
    handle_admin_audit_list,
)
from api.events import handle_get_ticket_events, handle_ticket_messages
from web_api.endpoint_operation_handlers import (
    handle_web_admin_endpoint_operation_get,
    handle_web_support_endpoint_operation_cancel,
)
from web_api.session_handlers import (
    handle_web_session_login,
    handle_web_session_logout,
    handle_web_session_me,
    handle_web_session_password_reset_request,
    handle_web_session_register,
)
from web_api.access_handlers import (
    handle_web_admin_access_audit,
    handle_web_admin_access_catalog,
    handle_web_admin_access_create_group,
    handle_web_admin_access_effective,
    handle_web_admin_access_group_members,
    handle_web_admin_access_group_permissions,
    handle_web_admin_access_group_queues,
    handle_web_admin_access_summary,
    handle_web_admin_access_update_group,
    handle_web_admin_access_user_password,
)
from web_api.support_handlers import (
    handle_web_admin_ticket_purge,
    handle_web_admin_ticket_purge_preview,
    handle_web_support_assign_ticket,
    handle_web_support_bootstrap,
    handle_web_support_approval_decision,
    handle_web_support_archive_ticket,
    handle_web_support_change_priority,
    handle_web_support_change_queue,
    handle_web_support_change_status,
    handle_web_support_cleanup_noise,
    handle_web_support_command_center,
    handle_web_support_hide_ticket,
    handle_web_support_reroute_ticket,
    handle_web_support_ticket_passport,
    handle_web_support_ticket_passport_evidence,
    handle_web_support_ticket_passport_evidence_candidates,
    handle_web_support_ticket_passport_evidence_link,
    handle_web_support_ticket_passport_evidence_update,
    handle_web_support_ticket_passport_generate,
    handle_web_support_ticket_passport_patch,
    handle_web_support_queue,
    handle_web_support_queue_mass_action,
    handle_web_support_queue_saved_view_create,
    handle_web_support_queue_saved_view_delete,
    handle_web_support_queue_saved_view_update,
    handle_web_support_queue_saved_views,
    handle_web_support_workspace_summary,
    handle_web_support_run_playbook,
    handle_web_support_run_tool,
    handle_web_support_send_message,
    handle_web_support_ticket_detail,
    handle_web_support_ticket_playbooks,
    handle_web_support_ticket_timeline,
    handle_web_support_ticket_tools,
    handle_web_support_ticket_worklog,
    handle_web_support_ticket_workspace,
    handle_web_support_unarchive_ticket,
    handle_web_support_unhide_ticket,
)
from web_api.admin_handlers import (
    handle_web_admin_bootstrap,
    handle_web_admin_device_token_revoke,
    handle_web_admin_device_tokens_list,
    handle_web_admin_device_tokens,
    handle_web_admin_device_restore,
    handle_web_admin_devices,
    handle_web_admin_devices_cleanup_env_duplicates,
    handle_web_admin_forms_current,
    handle_web_admin_forms_preferred,
    handle_web_admin_forms_process_preview,
    handle_web_admin_forms_publish,
    handle_web_admin_forms_route_preview,
    handle_web_admin_forms_save,
    handle_web_admin_forms_save_draft,
    handle_web_admin_forms_validate,
    handle_web_admin_helpdesk_model_policies,
    handle_web_admin_helpdesk_model_policy_deactivate,
    handle_web_admin_helpdesk_model_policy_diff,
    handle_web_admin_helpdesk_model_policy_rollback,
    handle_web_admin_helpdesk_model_publish_policy,
    handle_web_admin_helpdesk_model_publish_form_schema,
    handle_web_admin_helpdesk_model_publish_smart_view,
    handle_web_admin_helpdesk_model_publish_ticket_type,
    handle_web_admin_helpdesk_model_publish_from_form,
    handle_web_admin_helpdesk_model_republish_legacy_forms,
    handle_web_admin_helpdesk_model_ticket_type_deactivate,
    handle_web_admin_helpdesk_model_ticket_type_rollback,
    handle_web_admin_playbooks_catalog,
    handle_web_admin_playbooks_save,
    handle_web_admin_observer_quick,
    handle_web_admin_observer_trace_detail,
    handle_web_admin_observer_traces,
)
from web_api.endpoint_module_handlers import (
    handle_endpoint_module_capabilities,
    handle_endpoint_module_create_version,
    handle_endpoint_module_deprecate,
    handle_endpoint_module_publish,
    handle_endpoint_module_validate,
    handle_endpoint_module_run,
    handle_endpoint_modules_list,
)
from web_api.admin_inventory_handlers import (
    handle_web_admin_device_inventory,
    handle_web_admin_device_inventory_binding,
    handle_web_admin_device_inventory_binding_history,
    handle_web_admin_device_inventory_binding_update,
    handle_web_admin_device_inventory_collect,
    handle_web_admin_device_inventory_refresh_policy,
    handle_web_admin_device_inventory_refresh_policy_update,
    handle_web_admin_device_binding_suggestion_apply,
    handle_web_admin_device_binding_suggestion_ignore,
    handle_web_admin_device_binding_suggestions,
    handle_web_admin_device_presence,
    handle_web_admin_device_presence_collect,
    handle_web_admin_device_profiles,
    handle_web_admin_inventory_bindings_export_csv,
    handle_web_admin_inventory_bindings_import,
    handle_web_admin_inventory_bulk_operations,
    handle_web_admin_inventory_bulk_refresh,
    handle_web_admin_inventory_dashboard,
    handle_web_admin_inventory_export_csv,
    handle_web_admin_inventory_export_xlsx,
    handle_web_admin_inventory_report,
    handle_web_admin_inventory_refresh_policy,
    handle_web_admin_inventory_refresh_policy_update,
    handle_web_admin_inventory_refresh_runs,
)
from web_api.observer_integrity_handlers import (
    handle_web_admin_observer_integrity,
    handle_web_admin_observer_integrity_scan,
)
from web_api.device_operations_handlers import handle_web_admin_device_operations
from web_api.policy_health_handlers import (
    handle_web_admin_policy_health,
    handle_web_admin_policy_health_detail,
    handle_web_admin_policy_health_simulate,
)
from web_api.request_studio_handlers import (
    handle_web_admin_request_studio_capabilities,
    handle_web_admin_request_studio_publish,
    handle_web_admin_request_studio_publish_preview,
    handle_web_admin_request_studio_validate_draft,
)
from web_api.service_catalog_handlers import (
    handle_service_catalog_current,
    handle_service_catalog_offering,
    handle_service_catalog_preview,
    handle_service_catalog_service,
    handle_web_admin_service_catalog,
    handle_web_admin_service_catalog_offering,
    handle_web_admin_service_catalog_publish_offering,
    handle_web_admin_service_catalog_publish_service,
    handle_web_admin_service_catalog_retire_offering,
    handle_web_admin_service_catalog_retire_service,
    handle_web_admin_service_catalog_save_offering,
    handle_web_admin_service_catalog_save_service,
    handle_web_admin_service_catalog_service,
    handle_web_admin_service_catalog_service_offerings,
    handle_web_admin_service_catalog_simulate,
    handle_web_admin_service_catalog_validate_offering,
    handle_web_admin_service_catalog_validate_service,
)
from web_api.registry_handlers import (
    handle_registry_agent_claim_confirm,
    handle_registry_agent_consent_approve,
    handle_registry_agent_consent_deny,
    handle_registry_agent_consent_detail,
    handle_registry_agent_consents,
    handle_registry_agent_account_state,
    handle_registry_agent_account_login_request_create,
    handle_registry_agent_account_login_request_get,
    handle_registry_agent_account_session_confirmed_binding,
    handle_registry_agent_account_session_login,
    handle_registry_agent_account_session_logout,
    handle_registry_agent_account_session_registration_pending,
    handle_registry_agent_account_session_validate,
    handle_registry_agent_browser_pairing_create,
    handle_registry_agent_browser_pairing_get,
    handle_registry_agent_profile,
    handle_registry_agent_registration_form,
    handle_registry_agent_registration_status,
    handle_registry_options,
    handle_registry_profile_upsert,
    handle_web_admin_registry_account_sessions,
    handle_web_admin_registry_binding_revoke,
    handle_web_admin_registry_account_login_request_approve,
    handle_web_admin_registry_account_login_request_reject,
    handle_web_admin_registry_account_login_requests,
    handle_web_admin_registry_account_session_revoke,
    handle_web_admin_registry_account_session_timeline,
    handle_web_admin_registry_account_session_identity_explain,
    handle_web_admin_registry_audience_group_archive,
    handle_web_admin_registry_audience_group_members,
    handle_web_admin_registry_audience_group_preview_members,
    handle_web_admin_registry_audience_group_update,
    handle_web_admin_registry_audience_groups,
    handle_web_admin_registry_bulk_preview,
    handle_web_admin_registry_bulk_account_sessions_revoke,
    handle_web_admin_registry_bulk_devices_assign_department,
    handle_web_admin_registry_bulk_devices_assign_location,
    handle_web_admin_registry_bulk_devices_revoke_account_sessions,
    handle_web_admin_registry_bulk_people_assign_department,
    handle_web_admin_registry_department_archive,
    handle_web_admin_registry_department_update,
    handle_web_admin_registry_departments,
    handle_web_admin_registry_departments_merge,
    handle_web_admin_registry_departments_merge_preview,
    handle_web_admin_registry_device_account_events,
    handle_web_admin_registry_device_account_sessions,
    handle_web_admin_registry_device_bind_person,
    handle_web_admin_registry_device_responsible,
    handle_web_admin_registry_device_shared_users,
    handle_web_admin_registry_device_timeline,
    handle_web_admin_registry_device_transfer_owner,
    handle_web_admin_registry_device_transfer_owner_preview,
    handle_web_admin_registry_effective_identity,
    handle_web_admin_registry_export,
    handle_web_admin_registry_import_apply,
    handle_web_admin_registry_import_preview,
    handle_web_admin_registry_location_archive,
    handle_web_admin_registry_location_update,
    handle_web_admin_registry_locations,
    handle_web_admin_registry_locations_merge,
    handle_web_admin_registry_locations_merge_preview,
    handle_web_registry_browser_pairing_code_lookup,
    handle_web_registry_browser_pairing_get,
    handle_web_registry_browser_pairing_login_confirm,
    handle_web_registry_browser_pairing_registration_confirm,
    handle_web_admin_registry_people_create,
    handle_web_admin_registry_password_reset_request_complete,
    handle_web_admin_registry_password_reset_requests,
    handle_web_admin_registry_people_merge,
    handle_web_admin_registry_people_merge_preview,
    handle_web_admin_registry_person_archive,
    handle_web_admin_registry_person_identity_create,
    handle_web_admin_registry_person_identity_delete,
    handle_web_admin_registry_person_identity_update,
    handle_web_admin_registry_person_update,
    handle_web_admin_registry_person_audience,
    handle_web_admin_registry_profile_schema,
    handle_web_admin_registry_profile_schema_preview,
    handle_web_admin_registry_ui_user_disable,
    handle_web_admin_registry_ui_user_link_person,
    handle_web_admin_registry_policies,
    handle_web_admin_registry_policies_preview,
    handle_web_admin_registry_policies_reset,
    handle_web_admin_registry_quality_ignore,
    handle_web_admin_registry_quality_resolve,
    handle_web_admin_registry_quality_snooze,
    handle_web_admin_registry_registration_approve,
    handle_web_admin_registry_registration_reject,
    handle_web_admin_registry_registrations,
    handle_web_admin_registry_timeline,
    handle_web_admin_registry,
)
from web_api.reports_handlers import handle_web_reports_summary
from web_api.settings_handlers import handle_web_settings_payload, handle_web_settings_workflow_profiles_put
from web_api.realtime_handlers import handle_web_realtime_bootstrap
from web_api.ai_integration_handlers import handle_ai_integration_mcp_status
from tech.handlers import (
    handle_observer_settings_get,
    handle_observer_settings_patch,
    handle_tech_diagnostics_bundle,
    handle_tech_observer_search,
    handle_tech_observer_quick,
    handle_tech_overview,
    handle_tech_snapshot,
    handle_tech_locate,
    handle_tech_alerts,
    handle_tech_agents_audit,
    handle_tech_agent_timeline,
    handle_tech_agent_action,
    handle_tech_ticket_lifecycle,
    handle_tech_users_audit,
    handle_tech_admin_config_audit,
    handle_tech_logs,
    handle_tech_dismiss_item,
    handle_tech_operations_stuck,
    handle_tech_traces_runtime,
    handle_tech_traces_search,
    handle_tech_trace_detail,
    handle_tech_traces_rebuild,
    handle_tech_degradations_search,
    handle_tech_signatures_search,
    handle_tech_signature_detail,
)
from diagnostics.handlers import (
    handle_agent_recipe_create,
    handle_agent_recipe_primitives,
    handle_agent_recipe_publish,
    handle_agent_recipe_validate,
    handle_agent_recipes_list,
    handle_diagnostics_capabilities,
    handle_diagnostics_provider_config_get,
    handle_diagnostics_provider_config_put,
    handle_diagnostics_provider_configs,
    handle_diagnostics_profiles,
    handle_tool_presentation_delete,
    handle_tool_presentation_get,
    handle_tool_presentation_put,
    handle_runner_rollout_create_plan,
    handle_runner_rollout_get_plan,
    handle_runner_rollout_pause,
    handle_runner_rollout_promote_next_wave,
    handle_runner_rollout_refresh,
    handle_runner_rollout_resume,
    handle_runner_rollout_rollback,
    handle_runner_rollout_start_canary,
    handle_runner_rollout_summary,
    handle_admin_ticket_endpoint_device_mapping,
    handle_ticket_diagnostics_bundle_create,
    handle_ticket_diagnostics_bundle_get,
    handle_ticket_diagnostics_capability_run,
    handle_ticket_diagnostics_capabilities,
    handle_ticket_diagnostics_evidence,
    handle_ticket_diagnostics_evidence_patch,
    handle_ticket_diagnostics_finding_patch,
    handle_ticket_diagnostics_findings,
    handle_ticket_diagnostics_findings_evaluate,
    handle_ticket_diagnostics_manual_evidence,
    handle_ticket_diagnostics_manual_finding,
    handle_ticket_diagnostics_overview,
    handle_ticket_diagnostics_passport_attach_selected,
    handle_ticket_diagnostics_profile,
    handle_ticket_diagnostics_run_profile,
    handle_ticket_diagnostics_session_create,
    handle_ticket_diagnostics_session_detail,
    handle_ticket_diagnostics_sessions,
    handle_web_support_ticket_diagnostics_overview,
)


async def handle_health(_request: web.Request) -> web.Response:
    """GET /api/health — для smoke-тестов и мониторинга (без авторизации)."""
    return web.json_response({"status": "ok", "deploy_check": "verified", "run": "2025-03-17"})


def setup_routes(app: web.Application) -> None:
    """
    Регистрирует все маршруты приложения.
    
    Args:
        app: Экземпляр aiohttp.web.Application
    """
    app.add_routes([
        # ============================================================================
        # WebSocket Endpoints
        # ============================================================================
        web.get('/ws_ui', websocket_ui_handler),
        
        # ============================================================================
        # Static Pages
        # ============================================================================
        web.get('/', handle_index),
        web.get('/favicon.ico', handle_favicon),
        web.get('/favicon.svg', handle_webapp_public_asset),
        web.get('/assets/{asset_path:.*}', handle_webapp_asset),
        web.get('/app', handle_webapp_page),
        web.get('/app/{tail:.*}', handle_webapp_page),
        web.get('/login', handle_login_page),
        web.get('/admin', handle_admin_page),
        web.get('/support', handle_support_page),
        web.get('/queue', handle_public_queue_page),
        web.get('/queue/{queue_key}', handle_public_queue_page),
        web.get('/public_queue.css', handle_public_queue_css),
        web.get('/public_queue.js', handle_public_queue_js),
        web.get('/help', handle_help_page),
        web.get('/ticket.html', handle_ticket_page),
        web.get('/ticket/{ticket_id}', handle_ticket_page_by_id),
        
        # ============================================================================
        # Public Queue (Stage 10.2) — без авторизации
        # ============================================================================
        web.get('/public_api/queues', handle_public_queues),
        web.get('/public_api/queue/tickets', handle_public_queue_tickets),
        web.get('/public_api/queue/stats', handle_public_queue_stats),
        web.get('/public_api/ticket_forms/current', handle_ticket_form_pack_current),
        web.post('/public_api/tickets/create', handle_public_ticket_create),
        web.post('/public_api/tickets/{ticket_id}/authorize', handle_public_ticket_authorize),
        web.post('/public_api/tickets/{ticket_id}/feedback', handle_public_ticket_feedback),
        web.post('/public_api/tickets/{ticket_id}/reopen', handle_public_ticket_reopen),
        
        # ============================================================================
        # Health (для smoke-тестов и мониторинга)
        # ============================================================================
        web.get('/api/health', handle_health),

        # ============================================================================
        # Authentication API
        # ============================================================================
        web.post('/api/login', handle_login),
        web.post('/api/ui_login', handle_ui_login),  # UI user login
        web.get('/api/ui_session', handle_ui_session),
        web.post('/api/web/session/login', handle_web_session_login),
        web.post('/api/web/session/register', handle_web_session_register),
        web.post('/api/web/session/password-reset-requests', handle_web_session_password_reset_request),
        web.post('/api/web/session/logout', handle_web_session_logout),
        web.get('/api/web/session/me', handle_web_session_me),
        web.get('/api/web/support/bootstrap', handle_web_support_bootstrap),
        web.get('/api/web/support/command-center', handle_web_support_command_center),
        web.get('/api/web/support/approvals', handle_web_support_approvals),
        web.get('/api/web/support/workspace/summary', handle_web_support_workspace_summary),
        web.post('/api/web/support/workspace/cleanup-noise', handle_web_support_cleanup_noise),
        web.get('/api/web/support/queue', handle_web_support_queue),
        web.post('/api/web/support/queue/mass-action', handle_web_support_queue_mass_action),
        web.get('/api/web/support/queue/saved-views', handle_web_support_queue_saved_views),
        web.post('/api/web/support/queue/saved-views', handle_web_support_queue_saved_view_create),
        web.put('/api/web/support/queue/saved-views/{view_id}', handle_web_support_queue_saved_view_update),
        web.delete('/api/web/support/queue/saved-views/{view_id}', handle_web_support_queue_saved_view_delete),
        web.get('/api/web/support/people/{person_id}/history', handle_web_support_person_history),
        web.get('/api/web/support/tickets/{ticket_id}/history', handle_web_support_ticket_history),
        web.get('/api/web/support/tickets/{ticket_id}/context-pack', handle_web_support_ticket_context_pack),
        web.post('/api/web/support/tickets/{ticket_id}/llm-context/preview', handle_web_support_ticket_llm_context_preview),
        web.get('/api/web/support/tickets/{ticket_id}/workspace', handle_web_support_ticket_workspace),
        web.get('/api/web/support/tickets/{ticket_id}/timeline', handle_web_support_ticket_timeline),
        web.get('/api/web/support/tickets/{ticket_id}', handle_web_support_ticket_detail),
        web.get('/api/web/support/tickets/{ticket_id}/passport', handle_web_support_ticket_passport),
        web.post('/api/web/support/tickets/{ticket_id}/passport/generate', handle_web_support_ticket_passport_generate),
        web.patch('/api/web/support/tickets/{ticket_id}/passport', handle_web_support_ticket_passport_patch),
        web.get('/api/web/support/tickets/{ticket_id}/passport/evidence-candidates', handle_web_support_ticket_passport_evidence_candidates),
        web.post('/api/web/support/tickets/{ticket_id}/passport/evidence/link', handle_web_support_ticket_passport_evidence_link),
        web.patch('/api/web/support/tickets/{ticket_id}/passport/evidence/{evidence_id}', handle_web_support_ticket_passport_evidence_update),
        web.post('/api/web/support/tickets/{ticket_id}/passport/evidence', handle_web_support_ticket_passport_evidence),
        web.get('/api/web/support/tickets/{ticket_id}/diagnostics/overview', handle_web_support_ticket_diagnostics_overview),
        web.get('/api/web/support/tickets/{ticket_id}/diagnostics/capabilities', handle_ticket_diagnostics_capabilities),
        web.post('/api/web/support/tickets/{ticket_id}/diagnostics/capabilities/{capability_id}/run', handle_ticket_diagnostics_capability_run),
        web.put('/api/admin/tickets/{ticket_id}/endpoint-device-mapping', handle_admin_ticket_endpoint_device_mapping),
        web.get('/api/web/support/tickets/{ticket_id}/diagnostics/sessions', handle_ticket_diagnostics_sessions),
        web.post('/api/web/support/tickets/{ticket_id}/diagnostics/sessions', handle_ticket_diagnostics_session_create),
        web.get('/api/web/support/tickets/{ticket_id}/diagnostics/sessions/{session_id}', handle_ticket_diagnostics_session_detail),
        web.get('/api/web/support/tickets/{ticket_id}/diagnostics/evidence', handle_ticket_diagnostics_evidence),
        web.post('/api/web/support/tickets/{ticket_id}/diagnostics/evidence/manual', handle_ticket_diagnostics_manual_evidence),
        web.patch('/api/web/support/tickets/{ticket_id}/diagnostics/evidence/{evidence_id}', handle_ticket_diagnostics_evidence_patch),
        web.get('/api/web/support/tickets/{ticket_id}/diagnostics/findings', handle_ticket_diagnostics_findings),
        web.post('/api/web/support/tickets/{ticket_id}/diagnostics/findings/evaluate', handle_ticket_diagnostics_findings_evaluate),
        web.post('/api/web/support/tickets/{ticket_id}/diagnostics/findings/manual', handle_ticket_diagnostics_manual_finding),
        web.patch('/api/web/support/tickets/{ticket_id}/diagnostics/findings/{finding_id}', handle_ticket_diagnostics_finding_patch),
        web.post('/api/web/support/tickets/{ticket_id}/diagnostics/bundle', handle_ticket_diagnostics_bundle_create),
        web.get('/api/web/support/tickets/{ticket_id}/diagnostics/bundle/{bundle_id}', handle_ticket_diagnostics_bundle_get),
        web.get('/api/web/support/tickets/{ticket_id}/diagnostics/profile', handle_ticket_diagnostics_profile),
        web.post('/api/web/support/tickets/{ticket_id}/diagnostics/run-profile', handle_ticket_diagnostics_run_profile),
        web.post('/api/web/support/tickets/{ticket_id}/diagnostics/passport/attach-selected', handle_ticket_diagnostics_passport_attach_selected),
        web.post('/api/web/support/tickets/{ticket_id}/worklogs', handle_web_support_ticket_worklog),
        web.get('/api/web/support/tickets/{ticket_id}/tools', handle_web_support_ticket_tools),
        web.get('/api/web/support/tickets/{ticket_id}/playbooks', handle_web_support_ticket_playbooks),
        web.post('/api/web/support/tickets/{ticket_id}/messages', handle_web_support_send_message),
        web.post('/api/web/support/tickets/{ticket_id}/read', handle_ticket_mark_read),
        web.post('/api/web/support/tickets/{ticket_id}/status', handle_web_support_change_status),
        web.post('/api/web/support/tickets/{ticket_id}/assign', handle_web_support_assign_ticket),
        web.post('/api/web/support/tickets/{ticket_id}/queue', handle_web_support_change_queue),
        web.post('/api/web/support/tickets/{ticket_id}/priority', handle_web_support_change_priority),
        web.post('/api/web/support/tickets/{ticket_id}/reroute', handle_web_support_reroute_ticket),
        web.post('/api/web/support/tickets/{ticket_id}/hide', handle_web_support_hide_ticket),
        web.post('/api/web/support/tickets/{ticket_id}/unhide', handle_web_support_unhide_ticket),
        web.post('/api/web/support/tickets/{ticket_id}/archive', handle_web_support_archive_ticket),
        web.post('/api/web/support/tickets/{ticket_id}/unarchive', handle_web_support_unarchive_ticket),
        web.post('/api/web/support/tickets/{ticket_id}/approvals/{approval_id}/decision', handle_web_support_approval_decision),
        web.post('/api/web/support/tickets/{ticket_id}/tools/run', handle_web_support_run_tool),
        web.post('/api/web/support/tickets/{ticket_id}/playbooks/run', handle_web_support_run_playbook),
        web.post('/api/web/support/operations/{operation_id}/cancel', handle_web_support_endpoint_operation_cancel),
        web.get('/api/web/admin/bootstrap', handle_web_admin_bootstrap),
        web.post('/api/web/admin/tickets/purge/preview', handle_web_admin_ticket_purge_preview),
        web.post('/api/web/admin/tickets/purge', handle_web_admin_ticket_purge),
        web.get('/api/web/admin/capabilities', handle_diagnostics_capabilities),
        web.get('/api/web/tool-presentations', handle_tool_presentation_get),
        web.put('/api/web/tool-presentations', handle_tool_presentation_put),
        web.delete('/api/web/tool-presentations', handle_tool_presentation_delete),
        web.get('/api/web/admin/capabilities/provider-configs', handle_diagnostics_provider_configs),
        web.get('/api/web/admin/capabilities/provider-configs/{provider_id}', handle_diagnostics_provider_config_get),
        web.put('/api/web/admin/capabilities/provider-configs/{provider_id}', handle_diagnostics_provider_config_put),
        web.get('/api/web/admin/capabilities/runner-rollout', handle_runner_rollout_summary),
        web.post('/api/web/admin/capabilities/runner-rollout/plans', handle_runner_rollout_create_plan),
        web.get('/api/web/admin/capabilities/runner-rollout/plans/{plan_id}', handle_runner_rollout_get_plan),
        web.post('/api/web/admin/capabilities/runner-rollout/plans/{plan_id}/start-canary', handle_runner_rollout_start_canary),
        web.post('/api/web/admin/capabilities/runner-rollout/plans/{plan_id}/promote-next-wave', handle_runner_rollout_promote_next_wave),
        web.post('/api/web/admin/capabilities/runner-rollout/plans/{plan_id}/pause', handle_runner_rollout_pause),
        web.post('/api/web/admin/capabilities/runner-rollout/plans/{plan_id}/resume', handle_runner_rollout_resume),
        web.post('/api/web/admin/capabilities/runner-rollout/plans/{plan_id}/refresh', handle_runner_rollout_refresh),
        web.post('/api/web/admin/capabilities/runner-rollout/plans/{plan_id}/rollback', handle_runner_rollout_rollback),
        web.get('/api/web/admin/agent-recipes/primitives', handle_agent_recipe_primitives),
        web.get('/api/web/admin/agent-recipes', handle_agent_recipes_list),
        web.post('/api/web/admin/agent-recipes', handle_agent_recipe_create),
        web.post('/api/web/admin/agent-recipes/{recipe_id}/validate', handle_agent_recipe_validate),
        web.post('/api/web/admin/agent-recipes/{recipe_id}/publish', handle_agent_recipe_publish),
        web.get('/api/web/admin/diagnostics/providers/configs', handle_diagnostics_provider_configs),
        web.get('/api/web/admin/diagnostics/providers/configs/{provider_id}', handle_diagnostics_provider_config_get),
        web.put('/api/web/admin/diagnostics/providers/configs/{provider_id}', handle_diagnostics_provider_config_put),
        web.get('/api/web/admin/access/catalog', handle_web_admin_access_catalog),
        web.get('/api/web/admin/access/summary', handle_web_admin_access_summary),
        web.get('/api/web/admin/access/effective', handle_web_admin_access_effective),
        web.get('/api/web/admin/access/audit', handle_web_admin_access_audit),
        web.post('/api/web/admin/access/users/{user_login}/password', handle_web_admin_access_user_password),
        web.post('/api/web/admin/access/groups', handle_web_admin_access_create_group),
        web.patch('/api/web/admin/access/groups/{group_id}', handle_web_admin_access_update_group),
        web.put('/api/web/admin/access/groups/{group_id}/permissions', handle_web_admin_access_group_permissions),
        web.put('/api/web/admin/access/groups/{group_id}/members', handle_web_admin_access_group_members),
        web.put('/api/web/admin/access/groups/{group_id}/queues', handle_web_admin_access_group_queues),
        web.get('/api/web/admin/observer/quick', handle_web_admin_observer_quick),
        web.get('/api/web/admin/observer/integrity', handle_web_admin_observer_integrity),
        web.post('/api/web/admin/observer/integrity/scan', handle_web_admin_observer_integrity_scan),
        web.get('/api/web/admin/observer/traces', handle_web_admin_observer_traces),
        web.get('/api/web/admin/observer/trace-detail/{trace_id}', handle_web_admin_observer_trace_detail),
        web.get('/api/web/admin/observer/traces/{trace_id}', handle_web_admin_observer_trace_detail),
        web.get('/api/web/admin/observer/diagnostics/bundle', handle_tech_diagnostics_bundle),
        web.get('/api/web/admin/observer/runtime', handle_tech_traces_runtime),
        web.get('/api/web/admin/observer/settings', handle_observer_settings_get),
        web.patch('/api/web/admin/observer/settings', handle_observer_settings_patch),
        web.get('/api/web/admin/observer/signatures', handle_tech_signatures_search),
        web.get('/api/web/admin/observer/signatures/{error_signature}', handle_tech_signature_detail),
        web.get('/api/web/admin/observer/degradations', handle_tech_degradations_search),
        web.post('/api/web/admin/observer/traces/rebuild', handle_tech_traces_rebuild),
        web.get('/api/web/admin/tech/overview', handle_tech_overview),
        web.get('/api/web/admin/tech/snapshot', handle_tech_snapshot),
        web.get('/api/web/admin/tech/locate', handle_tech_locate),
        web.get('/api/web/admin/tech/alerts', handle_tech_alerts),
        web.get('/api/web/admin/tech/logs', handle_tech_logs),
        web.get('/api/web/admin/tech/agents/audit', handle_tech_agents_audit),
        web.get('/api/web/admin/tech/users/audit', handle_tech_users_audit),
        web.get('/api/web/admin/tech/operations/stuck', handle_tech_operations_stuck),
        web.get('/api/web/admin/ai-integration/mcp', handle_ai_integration_mcp_status),
        web.get('/api/web/admin/operations/{operation_id}', handle_web_admin_endpoint_operation_get),
        web.get('/api/web/admin/devices', handle_web_admin_devices),
        web.post('/api/web/admin/devices/cleanup_env_duplicates', handle_web_admin_devices_cleanup_env_duplicates),
        web.post('/api/web/admin/devices/{device_id}/restore', handle_web_admin_device_restore),
        web.get('/api/web/admin/inventory/dashboard', handle_web_admin_inventory_dashboard),
        web.post('/api/web/admin/inventory/bindings/import', handle_web_admin_inventory_bindings_import),
        web.get('/api/web/admin/inventory/bindings/export.csv', handle_web_admin_inventory_bindings_export_csv),
        web.get('/api/web/admin/inventory/export.csv', handle_web_admin_inventory_export_csv),
        web.get('/api/web/admin/inventory/export.xlsx', handle_web_admin_inventory_export_xlsx),
        web.get('/api/web/admin/inventory/reports', handle_web_admin_inventory_report),
        web.get('/api/web/admin/inventory/reports/{report_type}', handle_web_admin_inventory_report),
        web.post('/api/web/admin/inventory/bulk-refresh', handle_web_admin_inventory_bulk_refresh),
        web.get('/api/web/admin/inventory/bulk-operations', handle_web_admin_inventory_bulk_operations),
        web.get('/api/web/admin/inventory/refresh-runs', handle_web_admin_inventory_refresh_runs),
        web.get('/api/web/admin/inventory/refresh-policy', handle_web_admin_inventory_refresh_policy),
        web.put('/api/web/admin/inventory/refresh-policy', handle_web_admin_inventory_refresh_policy_update),
        web.get('/api/web/admin/devices/{device_id}/inventory', handle_web_admin_device_inventory),
        web.post('/api/web/admin/devices/{device_id}/inventory/collect', handle_web_admin_device_inventory_collect),
        web.get('/api/web/admin/devices/{device_id}/profiles', handle_web_admin_device_profiles),
        web.get('/api/web/admin/devices/{device_id}/binding-suggestions', handle_web_admin_device_binding_suggestions),
        web.post('/api/web/admin/devices/{device_id}/binding-suggestions/{suggestion_id}/apply', handle_web_admin_device_binding_suggestion_apply),
        web.post('/api/web/admin/devices/{device_id}/binding-suggestions/{suggestion_id}/ignore', handle_web_admin_device_binding_suggestion_ignore),
        web.get('/api/web/admin/devices/{device_id}/presence', handle_web_admin_device_presence),
        web.post('/api/web/admin/devices/{device_id}/presence/collect', handle_web_admin_device_presence_collect),
        web.get('/api/web/admin/devices/{device_id}/binding', handle_web_admin_device_inventory_binding),
        web.put('/api/web/admin/devices/{device_id}/binding', handle_web_admin_device_inventory_binding_update),
        web.get('/api/web/admin/devices/{device_id}/binding/history', handle_web_admin_device_inventory_binding_history),
        web.get('/api/web/admin/devices/{device_id}/inventory/refresh-policy', handle_web_admin_device_inventory_refresh_policy),
        web.put('/api/web/admin/devices/{device_id}/inventory/refresh-policy', handle_web_admin_device_inventory_refresh_policy_update),
        web.get('/api/web/admin/device-tokens', handle_web_admin_device_tokens_list),
        web.get('/api/web/admin/devices/{device_id}/tokens', handle_web_admin_device_tokens),
        web.post('/api/web/admin/devices/{device_id}/tokens/revoke', handle_web_admin_device_token_revoke),
        web.get('/api/web/admin/device-operations/{device_id}', handle_web_admin_device_operations),
        web.get('/api/web/admin/device-operations', handle_web_admin_device_operations),
        web.get('/api/web/admin/connection_policy', handle_admin_connection_policy_get),
        web.patch('/api/web/admin/connection_policy', handle_admin_connection_policy_patch),
        web.get('/api/web/admin/connection_requests', handle_admin_connection_requests_list),
        web.post('/api/web/admin/connection_requests/{device_id}/approve', handle_admin_connection_request_approve),
        web.post('/api/web/admin/connection_requests/{device_id}/reject', handle_admin_connection_request_reject),
        web.get('/api/web/admin/registry', handle_web_admin_registry),
        web.get('/api/web/admin/registry/profile-schema', handle_web_admin_registry_profile_schema),
        web.put('/api/web/admin/registry/profile-schema', handle_web_admin_registry_profile_schema),
        web.post('/api/web/admin/registry/profile-schema/preview', handle_web_admin_registry_profile_schema_preview),
        web.get('/api/web/admin/registry/identity/effective', handle_web_admin_registry_effective_identity),
        web.get('/api/web/admin/registry/identity/person/{person_id}/audience', handle_web_admin_registry_person_audience),
        web.get('/api/web/admin/registry/identity/session/{session_id}/explain', handle_web_admin_registry_account_session_identity_explain),
        web.get('/api/web/admin/registry/audience-groups', handle_web_admin_registry_audience_groups),
        web.post('/api/web/admin/registry/audience-groups', handle_web_admin_registry_audience_groups),
        web.patch('/api/web/admin/registry/audience-groups/{audience_group_id}', handle_web_admin_registry_audience_group_update),
        web.post('/api/web/admin/registry/audience-groups/{audience_group_id}/archive', handle_web_admin_registry_audience_group_archive),
        web.get('/api/web/admin/registry/audience-groups/{audience_group_id}/members', handle_web_admin_registry_audience_group_members),
        web.put('/api/web/admin/registry/audience-groups/{audience_group_id}/members', handle_web_admin_registry_audience_group_members),
        web.post('/api/web/admin/registry/audience-groups/{audience_group_id}/preview-members', handle_web_admin_registry_audience_group_preview_members),
        web.get('/api/web/admin/registry/registrations', handle_web_admin_registry_registrations),
        web.post('/api/web/admin/registry/registrations/{claim_id}/approve', handle_web_admin_registry_registration_approve),
        web.post('/api/web/admin/registry/registrations/{claim_id}/reject', handle_web_admin_registry_registration_reject),
        web.post('/api/web/admin/registry/bindings/{binding_id}/revoke', handle_web_admin_registry_binding_revoke),
        web.get('/api/web/admin/registry/devices/{device_id}/registration-timeline', handle_web_admin_registry_device_timeline),
        web.get('/api/web/admin/forms/current', handle_web_admin_forms_current),
        web.post('/api/web/admin/forms/route-preview', handle_web_admin_forms_route_preview),
        web.post('/api/web/admin/forms/process-preview', handle_web_admin_forms_process_preview),
        web.post('/api/web/admin/forms/save', handle_web_admin_forms_save),
        web.post('/api/web/admin/forms/save-draft', handle_web_admin_forms_save_draft),
        web.post('/api/web/admin/forms/validate', handle_web_admin_forms_validate),
        web.post('/api/web/admin/forms/publish', handle_web_admin_forms_publish),
        web.patch('/api/web/admin/forms/preferred', handle_web_admin_forms_preferred),
        web.get('/api/web/admin/helpdesk/policy-health', handle_web_admin_policy_health),
        web.get('/api/web/admin/helpdesk/policy-health/{template_code}', handle_web_admin_policy_health_detail),
        web.post('/api/web/admin/helpdesk/policy-health/simulate', handle_web_admin_policy_health_simulate),
        web.get('/api/web/admin/request-studio/capabilities', handle_web_admin_request_studio_capabilities),
        web.post('/api/web/admin/request-studio/validate-draft', handle_web_admin_request_studio_validate_draft),
        web.post('/api/web/admin/request-studio/publish-preview', handle_web_admin_request_studio_publish_preview),
        web.post('/api/web/admin/request-studio/publish', handle_web_admin_request_studio_publish),
        web.get('/api/web/admin/service-catalog', handle_web_admin_service_catalog),
        web.get('/api/web/admin/service-catalog/services/{service_code}', handle_web_admin_service_catalog_service),
        web.post('/api/web/admin/service-catalog/services/save-draft', handle_web_admin_service_catalog_save_service),
        web.post('/api/web/admin/service-catalog/services/{service_code}/validate', handle_web_admin_service_catalog_validate_service),
        web.post('/api/web/admin/service-catalog/services/{service_code}/publish', handle_web_admin_service_catalog_publish_service),
        web.post('/api/web/admin/service-catalog/services/{service_code}/retire', handle_web_admin_service_catalog_retire_service),
        web.get('/api/web/admin/service-catalog/services/{service_code}/offerings', handle_web_admin_service_catalog_service_offerings),
        web.get('/api/web/admin/service-catalog/offerings/{full_code}', handle_web_admin_service_catalog_offering),
        web.post('/api/web/admin/service-catalog/offerings/save-draft', handle_web_admin_service_catalog_save_offering),
        web.post('/api/web/admin/service-catalog/offerings/{full_code}/validate', handle_web_admin_service_catalog_validate_offering),
        web.post('/api/web/admin/service-catalog/offerings/{full_code}/publish', handle_web_admin_service_catalog_publish_offering),
        web.post('/api/web/admin/service-catalog/offerings/{full_code}/retire', handle_web_admin_service_catalog_retire_offering),
        web.post('/api/web/admin/service-catalog/simulate', handle_web_admin_service_catalog_simulate),
          web.get('/api/web/admin/helpdesk-model/policies', handle_web_admin_helpdesk_model_policies),
          web.post('/api/web/admin/helpdesk-model/policies/publish', handle_web_admin_helpdesk_model_publish_policy),
          web.post('/api/web/admin/helpdesk-model/policies/diff', handle_web_admin_helpdesk_model_policy_diff),
          web.post('/api/web/admin/helpdesk-model/policies/deactivate', handle_web_admin_helpdesk_model_policy_deactivate),
          web.post('/api/web/admin/helpdesk-model/policies/rollback', handle_web_admin_helpdesk_model_policy_rollback),
          web.post('/api/web/admin/helpdesk-model/ticket-types/publish', handle_web_admin_helpdesk_model_publish_ticket_type),
          web.post('/api/web/admin/helpdesk-model/ticket-types/deactivate', handle_web_admin_helpdesk_model_ticket_type_deactivate),
          web.post('/api/web/admin/helpdesk-model/ticket-types/rollback', handle_web_admin_helpdesk_model_ticket_type_rollback),
          web.post('/api/web/admin/helpdesk-model/form-schemas/publish', handle_web_admin_helpdesk_model_publish_form_schema),
          web.post('/api/web/admin/helpdesk-model/smart-views/publish', handle_web_admin_helpdesk_model_publish_smart_view),
        web.post('/api/web/admin/helpdesk-model/request-templates/publish-from-form', handle_web_admin_helpdesk_model_publish_from_form),
        web.post('/api/web/admin/helpdesk-model/request-templates/republish-legacy-forms', handle_web_admin_helpdesk_model_republish_legacy_forms),
        web.get('/api/web/admin/playbooks/catalog', handle_web_admin_playbooks_catalog),
        web.post('/api/web/admin/playbooks/save', handle_web_admin_playbooks_save),
        # Endpoint Recipe modules are exposed through a typed, Endpoint-owned BFF.
        web.get('/api/web/admin/endpoint-modules', handle_endpoint_modules_list),
        web.get('/api/web/admin/endpoint-modules/capabilities', handle_endpoint_module_capabilities),
        web.post('/api/web/admin/endpoint-modules', handle_endpoint_module_create_version),
        web.post('/api/web/admin/endpoint-modules/{module_key}/{version}/validate', handle_endpoint_module_validate),
        web.post('/api/web/admin/endpoint-modules/{module_key}/{version}/publish', handle_endpoint_module_publish),
        web.post('/api/web/admin/endpoint-modules/{module_key}/{version}/deprecate', handle_endpoint_module_deprecate),
        web.get('/api/admin/endpoint-modules', handle_endpoint_modules_list),
        web.post('/api/admin/endpoint-modules', handle_endpoint_module_create_version),
        web.post('/api/admin/endpoint-modules/{module_key}/{version}/validate', handle_endpoint_module_validate),
        web.post('/api/admin/endpoint-modules/{module_key}/{version}/publish', handle_endpoint_module_publish),
        web.post('/api/admin/endpoint-modules/{module_key}/{version}/deprecate', handle_endpoint_module_deprecate),
        web.post('/api/web/support/tickets/{ticket_id}/endpoint-modules/{module_key}/{version}/run', handle_endpoint_module_run),
        web.post('/api/support/tickets/{ticket_id}/endpoint-modules/{module_key}/{version}/run', handle_endpoint_module_run),
        web.get('/api/registry/options', handle_registry_options),
        web.post('/api/registry/profile', handle_registry_profile_upsert),
        web.post('/api/registry/agent/profile', handle_registry_agent_profile),
        web.get('/api/registry/agent/account-state', handle_registry_agent_account_state),
        web.post('/api/registry/agent/account-sessions/confirmed-binding', handle_registry_agent_account_session_confirmed_binding),
        web.post('/api/registry/agent/account-sessions/registration-pending', handle_registry_agent_account_session_registration_pending),
        web.post('/api/registry/agent/account-sessions/login', handle_registry_agent_account_session_login),
        web.get('/api/registry/agent/account-sessions/{session_id}/validate', handle_registry_agent_account_session_validate),
        web.post('/api/registry/agent/account-sessions/{session_id}/validate', handle_registry_agent_account_session_validate),
        web.post('/api/registry/agent/account-sessions/{session_id}/logout', handle_registry_agent_account_session_logout),
        web.post('/api/registry/agent/browser-pairings', handle_registry_agent_browser_pairing_create),
        web.get('/api/registry/agent/browser-pairings/{pairing_id}', handle_registry_agent_browser_pairing_get),
        web.post('/api/registry/agent/account-login-requests', handle_registry_agent_account_login_request_create),
        web.get('/api/registry/agent/account-login-requests/{request_id}', handle_registry_agent_account_login_request_get),
        web.get('/api/registry/agent/consents', handle_registry_agent_consents),
        web.get('/api/registry/agent/consents/{consent_id}', handle_registry_agent_consent_detail),
        web.post('/api/registry/agent/consents/{consent_id}/approve', handle_registry_agent_consent_approve),
        web.post('/api/registry/agent/consents/{consent_id}/deny', handle_registry_agent_consent_deny),
        web.get('/api/registry/agent/registration-form', handle_registry_agent_registration_form),
        web.get('/api/registry/agent/registration-status', handle_registry_agent_registration_status),
        web.post('/api/registry/agent/claims/{claim_id}/confirm', handle_registry_agent_claim_confirm),
        web.post('/api/web/registry/browser-pairings/lookup', handle_web_registry_browser_pairing_code_lookup),
        web.get('/api/web/registry/browser-pairings/{pairing_id}', handle_web_registry_browser_pairing_get),
        web.post('/api/web/registry/browser-pairings/{pairing_id}/login/confirm', handle_web_registry_browser_pairing_login_confirm),
        web.post('/api/web/registry/browser-pairings/{pairing_id}/registration/confirm', handle_web_registry_browser_pairing_registration_confirm),
        web.get('/api/web/requester/bootstrap', handle_web_requester_bootstrap),
        web.get('/api/web/requester/profile', handle_web_requester_profile),
        web.put('/api/web/requester/profile', handle_web_requester_profile_update),
        web.get('/api/web/requester/consents', handle_web_requester_consents),
        web.get('/api/web/requester/consents/{consent_id}', handle_web_requester_consent_detail),
        web.post('/api/web/requester/consents/{consent_id}/approve', handle_web_requester_consent_approve),
        web.post('/api/web/requester/consents/{consent_id}/deny', handle_web_requester_consent_deny),
        web.get('/api/web/requester/devices', handle_web_requester_devices),
        web.get('/api/web/requester/devices/{device_id}', handle_web_requester_device_detail),
        web.get('/api/web/requester/on-behalf/people', handle_web_requester_on_behalf_people),
        web.get('/api/web/requester/history', handle_web_requester_history),
        web.get('/api/web/requester/tickets', handle_web_requester_tickets),
        web.post('/api/web/requester/tickets', handle_web_requester_ticket_create),
        web.post('/api/web/requester/tickets/preview', handle_web_requester_ticket_preview),
        web.post('/api/web/requester/tickets/claim-public', handle_web_requester_ticket_claim_public),
        web.get('/api/web/requester/tickets/{ticket_id}/history', handle_web_requester_ticket_history),
        web.get('/api/web/requester/tickets/{ticket_id}', handle_web_requester_ticket_detail),
        web.post('/api/web/requester/tickets/{ticket_id}/message', handle_web_requester_ticket_message),
        web.post('/api/web/requester/tickets/{ticket_id}/close', handle_web_requester_ticket_close),
        web.post('/api/web/requester/tickets/{ticket_id}/feedback', handle_web_requester_ticket_feedback),
        web.post('/api/web/requester/tickets/{ticket_id}/reopen', handle_web_requester_ticket_reopen),
        web.get('/api/web/admin/history/search', handle_web_admin_history_search),
        web.get('/api/web/admin/registry/account-login-requests', handle_web_admin_registry_account_login_requests),
        web.post('/api/web/admin/registry/account-login-requests/{request_id}/approve', handle_web_admin_registry_account_login_request_approve),
        web.post('/api/web/admin/registry/account-login-requests/{request_id}/reject', handle_web_admin_registry_account_login_request_reject),
        web.get('/api/web/admin/registry/password-reset-requests', handle_web_admin_registry_password_reset_requests),
        web.post('/api/web/admin/registry/password-reset-requests/{request_id}/complete', handle_web_admin_registry_password_reset_request_complete),
        web.get('/api/web/admin/registry/account-sessions', handle_web_admin_registry_account_sessions),
        web.post('/api/web/admin/registry/bulk/preview', handle_web_admin_registry_bulk_preview),
        web.post('/api/web/admin/registry/bulk/account-sessions/revoke', handle_web_admin_registry_bulk_account_sessions_revoke),
        web.post('/api/web/admin/registry/bulk/devices/assign-location', handle_web_admin_registry_bulk_devices_assign_location),
        web.post('/api/web/admin/registry/bulk/devices/assign-department', handle_web_admin_registry_bulk_devices_assign_department),
        web.post('/api/web/admin/registry/bulk/devices/revoke-account-sessions', handle_web_admin_registry_bulk_devices_revoke_account_sessions),
        web.post('/api/web/admin/registry/bulk/people/assign-department', handle_web_admin_registry_bulk_people_assign_department),
        web.get('/api/web/admin/registry/departments', handle_web_admin_registry_departments),
        web.post('/api/web/admin/registry/departments', handle_web_admin_registry_departments),
        web.patch('/api/web/admin/registry/departments/{department_id}', handle_web_admin_registry_department_update),
        web.post('/api/web/admin/registry/departments/{department_id}/archive', handle_web_admin_registry_department_archive),
        web.post('/api/web/admin/registry/departments/merge/preview', handle_web_admin_registry_departments_merge_preview),
        web.post('/api/web/admin/registry/departments/merge', handle_web_admin_registry_departments_merge),
        web.get('/api/web/admin/registry/export', handle_web_admin_registry_export),
        web.post('/api/web/admin/registry/import/preview', handle_web_admin_registry_import_preview),
        web.post('/api/web/admin/registry/import/apply', handle_web_admin_registry_import_apply),
        web.get('/api/web/admin/registry/locations', handle_web_admin_registry_locations),
        web.post('/api/web/admin/registry/locations', handle_web_admin_registry_locations),
        web.patch('/api/web/admin/registry/locations/{location_id}', handle_web_admin_registry_location_update),
        web.post('/api/web/admin/registry/locations/{location_id}/archive', handle_web_admin_registry_location_archive),
        web.post('/api/web/admin/registry/locations/merge/preview', handle_web_admin_registry_locations_merge_preview),
        web.post('/api/web/admin/registry/locations/merge', handle_web_admin_registry_locations_merge),
        web.get('/api/web/admin/registry/policies', handle_web_admin_registry_policies),
        web.patch('/api/web/admin/registry/policies', handle_web_admin_registry_policies),
        web.post('/api/web/admin/registry/policies/preview', handle_web_admin_registry_policies_preview),
        web.post('/api/web/admin/registry/policies/reset', handle_web_admin_registry_policies_reset),
        web.post('/api/web/admin/registry/quality/{issue_key}/ignore', handle_web_admin_registry_quality_ignore),
        web.post('/api/web/admin/registry/quality/{issue_key}/snooze', handle_web_admin_registry_quality_snooze),
        web.post('/api/web/admin/registry/quality/{issue_key}/resolve', handle_web_admin_registry_quality_resolve),
        web.get('/api/web/admin/registry/timeline/{object_type}/{object_id}', handle_web_admin_registry_timeline),
        web.get('/api/web/admin/registry/devices/{device_id}/account-sessions', handle_web_admin_registry_device_account_sessions),
        web.get('/api/web/admin/registry/devices/{device_id}/account-events', handle_web_admin_registry_device_account_events),
        web.post('/api/web/admin/registry/devices/{device_id}/bind-person', handle_web_admin_registry_device_bind_person),
        web.post('/api/web/admin/registry/devices/{device_id}/transfer-owner/preview', handle_web_admin_registry_device_transfer_owner_preview),
        web.post('/api/web/admin/registry/devices/{device_id}/transfer-owner', handle_web_admin_registry_device_transfer_owner),
        web.post('/api/web/admin/registry/devices/{device_id}/shared-users', handle_web_admin_registry_device_shared_users),
        web.post('/api/web/admin/registry/devices/{device_id}/responsible', handle_web_admin_registry_device_responsible),
        web.get('/api/web/admin/registry/account-sessions/{session_id}/timeline', handle_web_admin_registry_account_session_timeline),
        web.post('/api/web/admin/registry/account-sessions/{session_id}/revoke', handle_web_admin_registry_account_session_revoke),
        web.post('/api/web/admin/registry/people', handle_web_admin_registry_people_create),
        web.post('/api/web/admin/registry/people/merge/preview', handle_web_admin_registry_people_merge_preview),
        web.post('/api/web/admin/registry/people/merge', handle_web_admin_registry_people_merge),
        web.post('/api/web/admin/registry/people/{person_id}/archive', handle_web_admin_registry_person_archive),
        web.patch('/api/web/admin/registry/people/{person_id}', handle_web_admin_registry_person_update),
        web.post('/api/web/admin/registry/people/{person_id}/identities', handle_web_admin_registry_person_identity_create),
        web.post('/api/web/admin/registry/ui-users/{user_login}/link-person', handle_web_admin_registry_ui_user_link_person),
        web.post('/api/web/admin/registry/ui-users/{user_login}/disable', handle_web_admin_registry_ui_user_disable),
        web.patch('/api/web/admin/registry/identities/{identity_id}', handle_web_admin_registry_person_identity_update),
        web.delete('/api/web/admin/registry/identities/{identity_id}', handle_web_admin_registry_person_identity_delete),
        web.get('/api/service-catalog/current', handle_service_catalog_current),
        web.post('/api/service-catalog/preview', handle_service_catalog_preview),
        web.get('/api/service-catalog/services/{service_code}', handle_service_catalog_service),
        web.get('/api/service-catalog/offerings/{full_code}', handle_service_catalog_offering),
        web.get('/api/web/quality/reviews', handle_quality_reviews),
        web.post('/api/web/quality/reviews/{review_id}/assign', handle_quality_reviews_assign),
        web.post('/api/web/quality/reviews/{review_id}/start', handle_quality_reviews_start),
        web.post('/api/web/quality/reviews/{review_id}/complete', handle_quality_reviews_complete),
        web.post('/api/web/quality/reviews/{review_id}/dismiss', handle_quality_reviews_dismiss),
        web.get('/api/web/quality/improvement-actions', handle_quality_improvement_actions),
        web.post('/api/web/quality/improvement-actions', handle_quality_improvement_actions_create),
        web.patch('/api/web/quality/improvement-actions/{action_id}', handle_quality_improvement_action_patch),
        web.post('/api/web/quality/improvement-actions/{action_id}/close', handle_quality_improvement_action_close),
        web.get('/api/web/quality/summary', handle_quality_summary),
        web.get('/api/web/quality/service-quality', handle_quality_service_quality),
        web.post('/api/web/quality/snapshots/recompute', handle_quality_snapshots_recompute),
        web.get('/api/web/quality/policies', handle_quality_policies),
        web.post('/api/web/quality/policies/save', handle_quality_policies_save),
        web.get('/api/web/problems/metrics/summary', handle_web_problem_metrics_summary),
        web.get('/api/web/problems', handle_web_problems_list),
        web.post('/api/web/problems', handle_web_problems_create),
        web.get('/api/web/problems/{problem_id}', handle_web_problem_get),
        web.post('/api/web/problems/{problem_id}/transition', handle_web_problem_transition),
        web.post('/api/web/problems/{problem_id}/link-ticket', handle_web_problem_link_ticket),
        web.post('/api/web/problems/{problem_id}/unlink-ticket/{ticket_id}', handle_web_problem_unlink_ticket),
        web.post('/api/web/problems/{problem_id}/affected-objects', handle_web_problem_affected_objects),
        web.post('/api/web/problems/{problem_id}/rca', handle_web_problem_rca_create),
        web.post('/api/web/problems/{problem_id}/rca/{rca_id}/submit-review', handle_web_problem_rca_submit),
        web.post('/api/web/problems/{problem_id}/rca/{rca_id}/approve', handle_web_problem_rca_approve),
        web.post('/api/web/problems/{problem_id}/known-error-draft', handle_web_problem_known_error_draft),
        web.post('/api/web/problems/{problem_id}/workaround-draft', handle_web_problem_workaround_draft),
        web.get('/api/web/problem-candidates', handle_web_problem_candidates),
        web.post('/api/web/problem-candidates/scan', handle_web_problem_candidates_scan),
        web.post('/api/web/problem-candidates/{candidate_id}/convert', handle_web_problem_candidate_convert),
        web.post('/api/web/problem-candidates/{candidate_id}/merge', handle_web_problem_candidate_merge),
        web.get('/api/web/problem-scanner/status', handle_web_problem_scanner_status),
        web.get('/api/web/problem-scanner/runs', handle_web_problem_scanner_runs),
        web.post('/api/web/problem-scanner/run', handle_web_problem_scanner_run),
        web.get('/api/web/changes/metrics/summary', handle_web_change_metrics_summary),
        web.get('/api/web/changes', handle_web_changes_list),
        web.post('/api/web/changes', handle_web_changes_create),
        web.post('/api/web/changes/from-problem/{problem_id}', handle_web_change_from_problem),
        web.post('/api/web/changes/from-improvement-action/{action_id}', handle_web_change_from_improvement_action),
        web.get('/api/web/changes/{change_id}', handle_web_change_get),
        web.post('/api/web/changes/{change_id}/transition', handle_web_change_transition),
        web.post('/api/web/changes/{change_id}/risk', handle_web_change_risk_create),
        web.post('/api/web/changes/{change_id}/risk/{assessment_id}/submit', handle_web_change_risk_submit),
        web.post('/api/web/changes/{change_id}/risk/{assessment_id}/approve', handle_web_change_risk_approve),
        web.post('/api/web/changes/{change_id}/plans', handle_web_change_plan_create),
        web.post('/api/web/changes/{change_id}/plans/{plan_id}/approve', handle_web_change_plan_approve),
        web.post('/api/web/changes/{change_id}/approvals/request', handle_web_change_approvals_request),
        web.post('/api/web/changes/{change_id}/approvals/{approval_id}/approve', handle_web_change_approval_decide),
        web.post('/api/web/changes/{change_id}/approvals/{approval_id}/reject', handle_web_change_approval_decide),
        web.post('/api/web/changes/{change_id}/schedule', handle_web_change_schedule),
        web.get('/api/web/changes/{change_id}/tasks', handle_web_change_tasks),
        web.post('/api/web/changes/{change_id}/tasks', handle_web_change_task_create),
        web.post('/api/web/changes/{change_id}/tasks/{task_id}/complete', handle_web_change_task_complete),
        web.post('/api/web/changes/{change_id}/pir', handle_web_change_pir_create),
        web.post('/api/web/changes/{change_id}/pir/{pir_id}/submit', handle_web_change_pir_submit),
        web.post('/api/web/changes/{change_id}/pir/{pir_id}/approve', handle_web_change_pir_approve),
        web.get('/api/web/change-windows', handle_web_change_windows),
        web.post('/api/web/change-windows', handle_web_change_windows_create),
        web.get('/api/web/change-policies', handle_web_change_policies),
        web.post('/api/web/change-policies/save', handle_web_change_policies_save),
        web.post('/api/web/change-policies/effective-preview', handle_web_change_policies_preview),
        web.get('/api/web/reports/summary', handle_web_reports_summary),
        web.get('/api/web/settings', handle_web_settings_payload),
        web.put('/api/web/settings/workflow_profiles', handle_web_settings_workflow_profiles_put),
        web.get('/api/web/notifications', handle_notifications_list),
        web.get('/api/web/notifications/unread_count', handle_notifications_unread_count),
        web.post('/api/web/notifications/read_all', handle_notifications_read_all),
        web.get('/api/web/notifications/preferences', handle_notification_preferences_get),
        web.post('/api/web/notifications/preferences', handle_notification_preferences_post),
        web.post('/api/web/notifications/{id}/read', handle_notification_mark_read),
        web.get('/api/web/settings/queues', handle_admin_queues_list),
        web.post('/api/web/settings/queues', handle_admin_queues_post),
        web.get('/api/web/settings/queues/{queue_id}', handle_admin_queues_get),
        web.patch('/api/web/settings/queues/{queue_id}', handle_admin_queues_patch),
        web.get('/api/web/settings/queues/{queue_id}/members', handle_admin_queue_members_list),
        web.put('/api/web/settings/queues/{queue_id}/members/{actor_id}', handle_admin_queue_members_put),
        web.delete('/api/web/settings/queues/{queue_id}/members/{actor_id}', handle_admin_queue_members_delete),
        web.get('/api/web/settings/queues/{queue_id}/ola_targets', handle_admin_ola_targets_get),
        web.put('/api/web/settings/queues/{queue_id}/ola_targets', handle_admin_ola_targets_put),
        web.get('/api/web/settings/routing_rules', handle_admin_routing_rules_list),
        web.post('/api/web/settings/routing_rules', handle_admin_routing_rules_post),
        web.patch('/api/web/settings/routing_rules/{rule_id}', handle_admin_routing_rules_patch),
        web.get('/api/web/settings/sla_policies', handle_admin_sla_policies_list),
        web.post('/api/web/settings/sla_policies', handle_admin_sla_policies_post),
        web.patch('/api/web/settings/sla_policies/{policy_id}', handle_admin_sla_policies_patch),
        web.post('/api/web/settings/sla_policies/{policy_id}/set_default', handle_admin_sla_policies_set_default),
        web.get('/api/web/settings/sla_policies/{policy_id}/targets', handle_admin_sla_targets_get),
        web.put('/api/web/settings/sla_policies/{policy_id}/targets', handle_admin_sla_targets_put),
        web.get('/api/web/settings/sla_policies/{policy_id}/priority_matrix', handle_admin_priority_matrix_get),
        web.put('/api/web/settings/sla_policies/{policy_id}/priority_matrix', handle_admin_priority_matrix_put),
        web.get('/api/web/settings/calendars', handle_admin_calendars_list),
        web.post('/api/web/settings/calendars', handle_admin_calendars_post),
        web.patch('/api/web/settings/calendars/{calendar_id}', handle_admin_calendars_patch),
        web.get('/api/web/settings/resolution_codes', handle_admin_resolution_codes_list),
        web.post('/api/web/settings/resolution_codes', handle_admin_resolution_codes_post),
        web.patch('/api/web/settings/resolution_codes/{code}', handle_admin_resolution_codes_patch),
        web.delete('/api/web/settings/resolution_codes/{code}', handle_admin_resolution_codes_delete),
        web.get('/api/web/settings/audit', handle_admin_audit_list),
        web.get('/api/web/realtime/bootstrap', handle_web_realtime_bootstrap),
        web.post('/api/users/me/password', handle_users_me_password_post),  # Stage 10: self-service password
        # Connection request flow (no auth: agent requests token)
        web.post('/api/connection_request', handle_connection_request),
        web.get('/api/connection_request/status', handle_connection_request_status),

        # ============================================================================
        # Tickets API (static paths before {ticket_id} to avoid "resolution_codes" as ticket_id)
        # ============================================================================
        web.post('/api/tickets/create/preview', handle_tickets_create_preview),
        web.post('/api/tickets/create', handle_tickets_create),
        web.get('/api/tickets', handle_tickets_list),
        web.get('/api/ticket_forms/current', handle_ticket_form_pack_current),
        web.get('/api/ticket_forms/packs', handle_ticket_form_packs_list),
        web.get('/api/ticket_forms/packs/{pack_key}/{version}', handle_ticket_form_pack_detail),
        web.post('/api/ticket_forms/packs/save', handle_ticket_form_pack_save),
        web.patch('/api/ticket_forms/packs/{pack_key}/{version}/preferred', handle_ticket_form_pack_set_preferred),
        web.get('/api/tickets/resolution_codes', handle_ticket_resolution_codes_list),
        web.get('/api/tickets/metrics/backlog', handle_ticket_metrics_backlog),
        web.get('/api/tickets/metrics/aging', handle_ticket_metrics_aging),
        web.get('/api/tickets/metrics/sla', handle_ticket_metrics_sla),
        web.get('/api/tickets/metrics/reopen_rate', handle_ticket_metrics_reopen_rate),
        web.get('/api/tickets/metrics/top', handle_ticket_metrics_top),
        web.get('/api/tickets/metrics/status_age', handle_ticket_metrics_status_age),
        web.post('/api/tickets/queues/{queue_id}/order/reset', handle_ticket_queue_order_reset),
        web.post('/api/tickets/archive', handle_tickets_archive),
        web.post('/api/tickets/bulk_assign', handle_tickets_bulk_assign),
        web.get('/api/tickets/{ticket_id}/diagnostics/capabilities', handle_ticket_diagnostics_capabilities),
        web.post('/api/tickets/{ticket_id}/diagnostics/capabilities/{capability_id}/run', handle_ticket_diagnostics_capability_run),
        web.get('/api/tickets/{ticket_id}/diagnostics/overview', handle_ticket_diagnostics_overview),
        web.get('/api/tickets/{ticket_id}/diagnostics/sessions', handle_ticket_diagnostics_sessions),
        web.post('/api/tickets/{ticket_id}/diagnostics/sessions', handle_ticket_diagnostics_session_create),
        web.get('/api/tickets/{ticket_id}/diagnostics/sessions/{session_id}', handle_ticket_diagnostics_session_detail),
        web.get('/api/tickets/{ticket_id}/diagnostics/evidence', handle_ticket_diagnostics_evidence),
        web.post('/api/tickets/{ticket_id}/diagnostics/evidence/manual', handle_ticket_diagnostics_manual_evidence),
        web.patch('/api/tickets/{ticket_id}/diagnostics/evidence/{evidence_id}', handle_ticket_diagnostics_evidence_patch),
        web.get('/api/tickets/{ticket_id}/diagnostics/findings', handle_ticket_diagnostics_findings),
        web.post('/api/tickets/{ticket_id}/diagnostics/findings/evaluate', handle_ticket_diagnostics_findings_evaluate),
        web.post('/api/tickets/{ticket_id}/diagnostics/findings/manual', handle_ticket_diagnostics_manual_finding),
        web.patch('/api/tickets/{ticket_id}/diagnostics/findings/{finding_id}', handle_ticket_diagnostics_finding_patch),
        web.post('/api/tickets/{ticket_id}/diagnostics/bundle', handle_ticket_diagnostics_bundle_create),
        web.get('/api/tickets/{ticket_id}/diagnostics/bundle/{bundle_id}', handle_ticket_diagnostics_bundle_get),
        web.get('/api/tickets/{ticket_id}/diagnostics/profile', handle_ticket_diagnostics_profile),
        web.post('/api/tickets/{ticket_id}/diagnostics/run-profile', handle_ticket_diagnostics_run_profile),
        web.post('/api/tickets/{ticket_id}/diagnostics/passport/attach-selected', handle_ticket_diagnostics_passport_attach_selected),
        web.get('/api/tickets/{ticket_id}', handle_ticket_get),
        web.get('/api/tickets/{ticket_id}/snapshot', handle_ticket_get_snapshot),  # New snapshot endpoint
        web.get('/api/tickets/{ticket_id}/observer', handle_ticket_get_observer_summary),
        web.post('/api/tickets/{ticket_id}/message', handle_ticket_send_message),
        web.post('/api/tickets/{ticket_id}/close', handle_ticket_close),
        web.post('/api/tickets/{ticket_id}/status', handle_ticket_status),
        web.post('/api/tickets/{ticket_id}/feedback', handle_ticket_feedback),
        web.post('/api/tickets/{ticket_id}/reopen', handle_ticket_reopen),
        web.post('/api/tickets/{ticket_id}/reroute', handle_ticket_reroute),
        web.post('/api/tickets/{ticket_id}/classify', handle_ticket_classify),
        web.post('/api/tickets/{ticket_id}/queue', handle_ticket_queue),
        web.post('/api/tickets/{ticket_id}/priority', handle_ticket_priority),
        web.post('/api/tickets/{ticket_id}/order', handle_ticket_order),
        web.post('/api/tickets/{ticket_id}/assign', handle_ticket_assign),
        web.post('/api/tickets/{ticket_id}/device', handle_ticket_bind_device),
        web.post('/api/tickets/{ticket_id}/read', handle_ticket_mark_read),
        web.post('/api/tickets/{ticket_id}/requester_profile', handle_ticket_requester_profile),
        web.get('/api/tickets/{ticket_id}/sla', handle_ticket_sla_get),
        web.post('/api/tickets/{ticket_id}/worklogs', handle_ticket_worklogs_post),
        web.get('/api/tickets/{ticket_id}/worklogs', handle_ticket_worklogs_list),
        web.get('/api/tickets/{ticket_id}/worklog_total', handle_ticket_worklog_total),
        web.get('/api/tickets/{ticket_id}/problems', handle_ticket_problems_get),
        web.post('/api/tickets/{ticket_id}/change_links', handle_ticket_change_links_post),
        web.get('/api/tickets/{ticket_id}/change_links', handle_ticket_change_links_list),
        web.delete('/api/tickets/{ticket_id}/change_links/{id}', handle_ticket_change_links_delete),
        # Stage 5: Relations, Watchers, KB, Metrics
        web.post('/api/tickets/{ticket_id}/links', handle_ticket_links_post),
        web.get('/api/tickets/{ticket_id}/links', handle_ticket_links_list),
        web.delete('/api/tickets/{ticket_id}/links/{link_id}', handle_ticket_links_delete),
        web.post('/api/tickets/{ticket_id}/parent', handle_ticket_parent_post),
        web.delete('/api/tickets/{ticket_id}/parent', handle_ticket_parent_delete),
        web.post('/api/tickets/{ticket_id}/watchers', handle_ticket_watchers_post),
        web.get('/api/tickets/{ticket_id}/watchers', handle_ticket_watchers_list),
        web.delete('/api/tickets/{ticket_id}/watchers/{actor_id}', handle_ticket_watchers_delete),
        
        # Phase D: Event Replay Endpoints
        web.get('/api/tickets/{ticket_id}/events', handle_get_ticket_events),
        web.get('/api/tickets/{ticket_id}/messages', handle_ticket_messages),  # Shortcut for chat messages
        # Stage 6: Notifications (static paths before {id})
        web.get('/api/notifications', handle_notifications_list),
        web.get('/api/notifications/unread_count', handle_notifications_unread_count),
        web.post('/api/notifications/read_all', handle_notifications_read_all),
        web.get('/api/notifications/preferences', handle_notification_preferences_get),
        web.post('/api/notifications/preferences', handle_notification_preferences_post),
        web.post('/api/notifications/{id}/read', handle_notification_mark_read),
        # Stage 7: Problems API (support/admin)
        web.post('/api/problems', handle_problems_create),
        web.get('/api/problems', handle_problems_list),
        web.get('/api/problems/{problem_id}', handle_problem_get),
        web.post('/api/problems/{problem_id}/status', handle_problem_status_post),
        web.post('/api/problems/{problem_id}/tickets', handle_problem_tickets_post),
        web.delete('/api/problems/{problem_id}/tickets/{ticket_id}', handle_problem_tickets_delete),
        
        # ============================================================================
        # Operations API
        # ============================================================================
        
        web.get('/api/diagnostics/capabilities', handle_diagnostics_capabilities),
        web.get('/api/diagnostics/providers/configs', handle_diagnostics_provider_configs),
        web.get('/api/diagnostics/providers/configs/{provider_id}', handle_diagnostics_provider_config_get),
        web.put('/api/diagnostics/providers/configs/{provider_id}', handle_diagnostics_provider_config_put),
        web.get('/api/diagnostics/profiles', handle_diagnostics_profiles),
        
        # ============================================================================
        # Admin API
        # ============================================================================
        # Stage 10: Admin Users API (feature-flagged: AUTH_UI_DB_USERS_ENABLED)
        web.get('/api/admin/users', handle_admin_users_list),
        web.post('/api/admin/users', handle_admin_users_post),
        web.get('/api/admin/users/{user_login}', handle_admin_users_get),
        web.patch('/api/admin/users/{user_login}', handle_admin_users_patch),
        web.post('/api/admin/users/{user_login}/password', handle_admin_users_password_post),
        web.post('/api/admin/users/{user_login}/deactivate', handle_admin_users_deactivate_post),
        # Connection request policy and pending requests (admin)
        web.get('/api/admin/connection_policy', handle_admin_connection_policy_get),
        web.patch('/api/admin/connection_policy', handle_admin_connection_policy_patch),
        web.get('/api/admin/connection_requests', handle_admin_connection_requests_list),
        web.post('/api/admin/connection_requests/{device_id}/approve', handle_admin_connection_request_approve),
        web.post('/api/admin/connection_requests/{device_id}/reject', handle_admin_connection_request_reject),
        # Stage 9: Admin Config API (feature-flagged)
        web.get('/api/admin/tickets/queues', handle_admin_queues_list),
        web.post('/api/admin/tickets/queues', handle_admin_queues_post),
        web.get('/api/admin/tickets/queues/{queue_id}', handle_admin_queues_get),
        web.patch('/api/admin/tickets/queues/{queue_id}', handle_admin_queues_patch),
        web.get('/api/admin/tickets/queues/{queue_id}/members', handle_admin_queue_members_list),
        web.put('/api/admin/tickets/queues/{queue_id}/members/{actor_id}', handle_admin_queue_members_put),
        web.delete('/api/admin/tickets/queues/{queue_id}/members/{actor_id}', handle_admin_queue_members_delete),
        web.get('/api/admin/tickets/resolution_codes', handle_admin_resolution_codes_list),
        web.post('/api/admin/tickets/resolution_codes', handle_admin_resolution_codes_post),
        web.patch('/api/admin/tickets/resolution_codes/{code}', handle_admin_resolution_codes_patch),
        web.delete('/api/admin/tickets/resolution_codes/{code}', handle_admin_resolution_codes_delete),
        web.get('/api/admin/tickets/routing_rules', handle_admin_routing_rules_list),
        web.post('/api/admin/tickets/routing_rules', handle_admin_routing_rules_post),
        web.patch('/api/admin/tickets/routing_rules/{rule_id}', handle_admin_routing_rules_patch),
        web.get('/api/admin/tickets/sla_policies', handle_admin_sla_policies_list),
        web.post('/api/admin/tickets/sla_policies', handle_admin_sla_policies_post),
        web.patch('/api/admin/tickets/sla_policies/{policy_id}', handle_admin_sla_policies_patch),
        web.post('/api/admin/tickets/sla_policies/{policy_id}/set_default', handle_admin_sla_policies_set_default),
        web.get('/api/admin/tickets/sla_policies/{policy_id}/targets', handle_admin_sla_targets_get),
        web.put('/api/admin/tickets/sla_policies/{policy_id}/targets', handle_admin_sla_targets_put),
        web.get('/api/admin/tickets/sla_policies/{policy_id}/priority_matrix', handle_admin_priority_matrix_get),
        web.put('/api/admin/tickets/sla_policies/{policy_id}/priority_matrix', handle_admin_priority_matrix_put),
        web.get('/api/admin/tickets/calendars', handle_admin_calendars_list),
        web.post('/api/admin/tickets/calendars', handle_admin_calendars_post),
        web.patch('/api/admin/tickets/calendars/{calendar_id}', handle_admin_calendars_patch),
        web.get('/api/admin/tickets/queues/{queue_id}/ola_targets', handle_admin_ola_targets_get),
        web.put('/api/admin/tickets/queues/{queue_id}/ola_targets', handle_admin_ola_targets_put),
        web.get('/api/admin/tickets/audit', handle_admin_audit_list),
        # Tech observability panel (read-only)
        web.get('/api/admin/tech/overview', handle_tech_overview),
        web.get('/api/admin/tech/alerts', handle_tech_alerts),
        web.get('/api/admin/tech/logs', handle_tech_logs),
        web.post('/api/admin/tech/dismiss', handle_tech_dismiss_item),
        web.get('/api/admin/tech/agents/audit', handle_tech_agents_audit),
        web.get('/api/admin/tech/agents/{device_id}/timeline', handle_tech_agent_timeline),
        web.post('/api/admin/tech/agents/{device_id}/actions', handle_tech_agent_action),
        web.get('/api/admin/tech/tickets/{ticket_id}/lifecycle', handle_tech_ticket_lifecycle),
        web.get('/api/admin/tech/users/audit', handle_tech_users_audit),
        web.get('/api/admin/tech/admin-config/audit', handle_tech_admin_config_audit),
        web.get('/api/admin/tech/operations/stuck', handle_tech_operations_stuck),
        web.get('/api/admin/tech/observer/quick', handle_tech_observer_quick),
        web.get('/api/admin/tech/observer/search', handle_tech_observer_search),
        web.get('/api/admin/tech/diagnostics/bundle', handle_tech_diagnostics_bundle),
        web.get('/api/admin/settings/observer', handle_observer_settings_get),
        web.patch('/api/admin/settings/observer', handle_observer_settings_patch),
        web.get('/api/admin/tech/traces/runtime', handle_tech_traces_runtime),
        web.get('/api/admin/tech/traces', handle_tech_traces_search),
        web.post('/api/admin/tech/traces/rebuild', handle_tech_traces_rebuild),
        web.get('/api/admin/tech/traces/{trace_id}', handle_tech_trace_detail),
        web.get('/api/admin/tech/degradations', handle_tech_degradations_search),
        web.get('/api/admin/tech/signatures', handle_tech_signatures_search),
        web.get('/api/admin/tech/signatures/{error_signature}', handle_tech_signature_detail),
        
        # ============================================================================
        # Uploads API
        # ============================================================================
        web.post('/api/upload', handle_upload),
        web.get('/api/artifacts/{artifact_id}/download', handle_artifact_download),
        
        # ============================================================================
        # Protocol Documentation
        # ============================================================================
        
        # ============================================================================
        # Commands API
        # ============================================================================
        
        # ============================================================================
        # Playbook API (Этап 4 MVP)
        # ============================================================================
        web.post('/api/playbooks/runs', handle_start_playbook_run),
        
        # ============================================================================
        # Additional HTML Pages
        # ============================================================================
        web.get('/test_simple', handle_test_simple),
        web.get('/ws_ui_test', handle_ws_ui_test),
    ])
