from __future__ import annotations

from typing import List

from diagnostics.capability_models import CapabilityDescriptor


def list_static_capabilities() -> List[CapabilityDescriptor]:
    return [
        CapabilityDescriptor(
            id="observer.ticket.summary",
            title="Observer: ticket summary",
            description="Summarize existing observer traces for a ticket.",
            provider_id="observer",
            provider_type="observer_provider",
            execution_target="observer_query",
            requires_device=False,
            requires_agent_online=False,
            required_permission="observer.trace.view",
            source="observer",
            evidence={
                "produces_evidence": True,
                "kind": "observer.summary",
                "domain": "observer",
                "perspective": "observer",
                "passport_eligible": True,
            },
        ),
        CapabilityDescriptor(
            id="observer.trace.bundle",
            title="Observer: trace bundle",
            description="Bundle observer traces for diagnostic review.",
            provider_id="observer",
            provider_type="observer_provider",
            execution_target="observer_query",
            requires_device=False,
            requires_agent_online=False,
            required_permission="observer.trace.view",
            source="observer",
            evidence={
                "produces_evidence": True,
                "kind": "observer.trace_bundle",
                "domain": "observer",
                "perspective": "observer",
                "passport_eligible": True,
            },
        ),
        CapabilityDescriptor(
            id="remote_assist.request_view",
            title="Remote Assist: request view",
            description="Reserve a remote assist view request as a session capability.",
            provider_id="remote_assist",
            provider_type="remote_assist_provider",
            execution_target="remote_assist",
            requires_device=True,
            requires_agent_online=True,
            requires_consent=True,
            requires_policy=True,
            required_permission="remote_assist.request",
            policy_key="remote_assist.enabled",
            source="remote_assist",
            evidence={
                "produces_evidence": True,
                "kind": "remote_assist.session",
                "domain": "remote_assist",
                "perspective": "remote_assist",
                "passport_eligible": True,
            },
        ),
        CapabilityDescriptor(
            id="remote_assist.session.summary",
            title="Remote Assist: session summary",
            description="Reserve a remote assist session summary capability.",
            provider_id="remote_assist",
            provider_type="remote_assist_provider",
            execution_target="remote_assist",
            requires_device=True,
            requires_agent_online=True,
            required_permission="remote_assist.view",
            source="remote_assist",
            evidence={
                "produces_evidence": True,
                "kind": "remote_assist.summary",
                "domain": "remote_assist",
                "perspective": "remote_assist",
                "passport_eligible": True,
            },
        ),
        CapabilityDescriptor(
            id="manual.visual_check",
            title="Manual: visual check",
            description="Record a manual operator observation.",
            provider_id="manual",
            provider_type="manual_provider",
            execution_target="manual",
            required_permission="ticket.passport.manage",
            source="manual",
            evidence={
                "produces_evidence": True,
                "kind": "manual.visual_check",
                "domain": "manual",
                "perspective": "manual",
                "passport_eligible": True,
            },
        ),
        CapabilityDescriptor(
            id="manual.vendor_response",
            title="Manual: vendor response",
            description="Record a vendor response as manual diagnostic evidence.",
            provider_id="manual",
            provider_type="manual_provider",
            execution_target="manual",
            required_permission="ticket.passport.manage",
            source="manual",
            evidence={
                "produces_evidence": True,
                "kind": "manual.vendor_response",
                "domain": "manual",
                "perspective": "manual",
                "passport_eligible": True,
            },
        ),
    ]
