-- Migration 033: Playbook Engine tables
-- Применить от пользователя с правами на запись (не pc_client_ro).
-- Либо: из каталога server с заданным DATABASE_URL: alembic upgrade head

BEGIN;

CREATE TABLE playbook (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR(128) NOT NULL,
    name TEXT NOT NULL,
    domain VARCHAR(64),
    owner VARCHAR(128),
    archived BOOLEAN NOT NULL DEFAULT false
);
CREATE UNIQUE INDEX ix_playbook_key ON playbook (key);
CREATE INDEX ix_playbook_domain ON playbook (domain);

CREATE TABLE playbook_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playbook_id BIGINT NOT NULL REFERENCES playbook(id) ON DELETE CASCADE,
    version VARCHAR(32) NOT NULL,
    manifest_json JSONB,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_at TIMESTAMPTZ
);
CREATE INDEX ix_playbook_version_playbook_id ON playbook_version (playbook_id);
CREATE UNIQUE INDEX ix_playbook_version_playbook_version ON playbook_version (playbook_id, version);

CREATE TABLE playbook_step (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playbook_version_id BIGINT NOT NULL REFERENCES playbook_version(id) ON DELETE CASCADE,
    step_key VARCHAR(64) NOT NULL,
    order_no INTEGER NOT NULL,
    type VARCHAR(32) NOT NULL DEFAULT 'run_tool',
    tool TEXT,
    params_template_json JSONB,
    if_expr TEXT,
    timeout_sec INTEGER,
    retry_policy_json JSONB,
    continue_on_error BOOLEAN NOT NULL DEFAULT false,
    parallel_group VARCHAR(32)
);
CREATE INDEX ix_playbook_step_playbook_version_id ON playbook_step (playbook_version_id);
CREATE INDEX ix_playbook_step_order ON playbook_step (playbook_version_id, order_no);

CREATE TABLE playbook_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playbook_version_id BIGINT NOT NULL REFERENCES playbook_version(id) ON DELETE RESTRICT,
    device_id VARCHAR(36) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    scheduled_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    trigger_type VARCHAR(32),
    context_json JSONB,
    error_code TEXT,
    error_message TEXT
);
CREATE INDEX ix_playbook_run_playbook_version_id ON playbook_run (playbook_version_id);
CREATE INDEX ix_playbook_run_device_id ON playbook_run (device_id);
CREATE INDEX ix_playbook_run_status ON playbook_run (status);
CREATE INDEX ix_playbook_run_scheduled_at ON playbook_run (scheduled_at);

CREATE TABLE playbook_step_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playbook_run_id BIGINT NOT NULL REFERENCES playbook_run(id) ON DELETE CASCADE,
    playbook_step_id BIGINT NOT NULL REFERENCES playbook_step(id) ON DELETE RESTRICT,
    attempt INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    operation_id VARCHAR(36),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    input_json JSONB,
    output_json JSONB,
    error_json JSONB,
    trace_id VARCHAR(36)
);
CREATE INDEX ix_playbook_step_run_playbook_run_id ON playbook_step_run (playbook_run_id);
CREATE INDEX ix_playbook_step_run_operation_id ON playbook_step_run (operation_id);

UPDATE alembic_version SET version_num = '033';

COMMIT;
